<?php

namespace App\Providers;

use App\Contracts\ImageSystem;
use App\Extensions\Image\StoreToLocal;
use Illuminate\Support\ServiceProvider;

class ImageServiceProvider extends ServiceProvider
{
    protected $defer = true;

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(ImageSystem::class, function ($app) {
            return new StoreToLocal();
        });
    }

    public function provides()
    {
        return [ImageSystem::class]; // TODO: Change the autogenerated stub
    }
}
